### ISSUE TITLE
Need help about dismiss after scanned 

### ISSUE THREAD

**Issue by nuieskater** [rdlabo-team/capacitor-codescanner#1]
I’m adapted to work with ionic-vue. 
Plugin work very fast, smooth. But i dnt knw how to dismiss or close it. 

Thanks

**Comment by rdlabo** [comment]
I prepare close button top-left. Is this displayed?

![ios](https://user-images.githubusercontent.com/9690024/80788271-a5840e00-8bc3-11ea-96a9-3aade0234ef6.jpg)

**Comment by nuieskater** [comment]
Thanks for answer. 
 Yes I saw. but i mean automate dismiss.

**Comment by rdlabo** [comment]
Do you want to close automatically after scan once?
This plugin don't have this function or option. If you implement, I will review and marge. 
Thanks.

**Comment by nuieskater** [comment]
After spend 1 day reading swift, Capacitor and your code.. my problem solved 
By parsing  data back to regular Javascript and catch listener and call 

`  DispatchQueue.main.async {  rootViewController.dismiss()  } `


Work like a charm 🤝  Thanks you.
-IonicVue , Capacitor.
